CXX=g++
CXXFLAGS=-std=c++14 -Wall -pthread

thread:
	$(CXX) $(CXXFLAGS) -o thread thread_example.cpp

redirect:
	$(CXX) $(CXXFLAGS) -o redirect output_redirection_example.cpp
clean:
	rm -f *.o thread	
